### ISSUE TITLE
I'm getting an error while trying to run migrations

### ISSUE THREAD

**Issue by abdulhameed** [xhizor/django-rent-a-car#1]
Hi @xhizor , please help me with this problem i'm struggling with.
I have installed all requirements and dependencies, when i try to run migration i get the following error

Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

**Comment by xhizor** [comment]
https://stackoverflow.com/questions/35184458/no-module-named-django-but-it-is-installed
